apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

namespace: ${NAMESPACE}

images:
  - name: PLACEHOLDER_POSTGRES_IMAGE
    newName: ${POSTGRES_IMAGE}
  - name: PLACEHOLDER_BACKEND_IMAGE
    newName: ${BACKEND_IMAGE}
  - name: PLACEHOLDER_FRONTEND_IMAGE
    newName: ${BACKEND_IMAGE}