kind: Secret
apiVersion: v1
metadata:
  name: synregistry-acr-secret
  namespace: orchestration
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzeW5yZWdpc3RyeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoid29ya3Nob3AiLCJwYXNzd29yZCI6Ijc0QUwxc01FaHhMdlVzaVV0MCtjcTdEaGQxd2dxdkFVelJOSjdDUFpMZStBQ1JDUlYxUTMiLCJhdXRoIjoiZDI5eWEzTm9iM0E2TnpSQlRERnpUVVZvZUV4MlZYTnBWWFF3SzJOeE4wUm9aREYzWjNGMlFWVjZVazVLTjBOUVdreGxLMEZEVWtOU1ZqRlJNdz09In19fQ==
type: kubernetes.io/dockerconfigjson
