apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginxconf-configmap
  namespace: PLACEHOLDER_NAMESPACE
data:
  default.conf: |
    server {
        listen 8080;
    
        # Serve static files from /usr/share/nginx/html
        location / {
            root /usr/share/nginx/html;
            index index.html;

            add_header X-Pod-Hostname $hostname;
        }
    }
